apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: photoalbum
  POSTGRES_USER: photoalbum
  POSTGRES_PASSWORD: photoalbumpass
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "123456789"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: ".openshiftapps.com"
  # Ha 403 CSRF lesz login/feltöltésnél, akkor ezt majd állítsd be:
  # DJANGO_CSRF_TRUSTED_ORIGINS: "https://REPLACE_ME_ROUTE_HOST"
  DATABASE_URL: "postgres://photoalbum:photoalbumpass@postgres:5432/photoalbum"
  DJANGO_MEDIA_ROOT: "/data/media"