apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: photoalbum-git
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: photoalbum-git
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/stefflermateBME/photoalbum.git"
      ref: "main"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "photoalbum-git:latest"
  triggers: []   # szándékosan üres, hogy biztosan kézzel indítsuk