apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: photoalbum-git
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: photoalbum-git
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      # URL and branch of your GitHub repository
      uri: "https://github.com/stefflermateBME/photoalbum.git"
      ref: "main"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "photoalbum-git:latest"
  triggers:
    # Trigger a new build whenever a commit is pushed to GitHub.
    # Replace <my-github-secret> with a strong random string and reuse it in GitHub webhooks.
    - type: GitHub
      github:
        secret: 123456789
    # Trigger a new build whenever the build configuration itself changes (e.g. this YAML is updated)
    - type: ConfigChange
      configChange: {}
