apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: photoalbum
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      volumes:                      # âœ… ITT kell lennie
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: staticfiles
          emptyDir: {}

      containers:
        - name: photoalbum
          image: image-registry.openshift-image-registry.svc:5000/photoalbum/photoalbum:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: media-storage
              mountPath: /data/media
            - name: staticfiles
              mountPath: /app/staticfiles